spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestaomasterx_db?createDatabaseIfNotExist=true
    username: root
    password: Developer@100Senha!
    driver-class-name: com.mysql.cj.jdbc.Driver